//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jigsaw_2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jigsaw_2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eduard mane 
        ///51
        ///pablo pikaso 
        ///91
        ///rafael 
        ///37
        ///piter pol rubens 
        ///62
        ///jan vermer 
        ///42
        ///teodor zeriko 
        ///32
        ///djura jaksic 
        ///48
        ///francisko goja 
        ///82
        ///
        ///bernardo 
        ///bertoluci
        ///akira 
        ///kurosava
        ///nikita 
        ///mihalkov
        ///zan luk 
        ///godar
        ///vim 
        ///venders
        ///fatih 
        ///akin
        ///verner 
        ///hercog
        ///alfred 
        ///hickok
        ///
        ///morfijum 
        ///analgetik
        ///diazepam 
        ///anksiolitici
        ///ampicilin 
        ///antibiotik
        ///fluvoksamin 
        ///antidepresiv
        ///rezorcinol 
        ///antiseptik
        ///flunizolid 
        ///antiasmatik
        ///laktuloza 
        ///laksativ
        ///pirantel 
        ///antelmintik
        ///
        ///golub 
        ///niski visokol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CouplingsList {
            get {
                return ResourceManager.GetString("CouplingsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK
        ///Ej
        ///Ep
        ///Iš
        ///Le
        ///Om
        ///Uf
        ///WC
        ///ao
        ///ej
        ///ih
        ///im
        ///iz
        ///ja
        ///je
        ///jo
        ///ju
        ///ka
        ///mb
        ///ol
        ///si
        ///su
        ///te
        ///tu
        ///ud
        ///uf
        ///um
        ///ur
        ///uz
        ///wc
        ///za
        ///zu
        ///će
        ///ću
        ///Ajd
        ///Ala
        ///Alo
        ///Alu
        ///Ane
        ///Anu
        ///BMW
        ///Bua
        ///Buš
        ///CNN
        ///Cea
        ///DDR
        ///DNK
        ///Edi
        ///Eme
        ///Eno
        ///Eto
        ///Evo
        ///FSB
        ///Fuj
        ///GRU
        ///Gog
        ///Idi
        ///Igi
        ///Igo
        ///Ime
        ///Ira
        ///Iru
        ///Ise
        ///Jao
        ///Jer
        ///Kul
        ///Lao
        ///Lav
        ///Lin
        ///MBH
        ///MGU
        ///Moj
        ///Naš
        ///Nek
        ///Oho
        ///Ovi
        ///Oče
        ///Pri
        ///Psu
        ///Reč
        ///Rus
        ///SMI
        ///Teg
        ///USB
        ///Ura
        ///Uði
        ///VTO
        ///Zam
        ///Zar
        ///Zig
        ///ada
        ///ako
        ///akt
        ///alo
        ///alu
        ///amo
        ///api
        ///apn
        ///aps
        ///baš
        ///beo
        ///ber
        ///bes
        ///bez
        ///bež
        ///bih
        ///bič
        ///boj
        ///bok
        ///bol
        ///bos
        ///bre
        ///brk
        ///bul
        ///buð
        ///cak
        ///cev
        ///cik
        ///crn
        ///crv
        ///dah
        ///daj
        ///dao
        ///dar
        ///dat
        ///daš
        ///deo
        ///dno
        ///dnu
        ///dok
        ///dom
        ///duh
        ///duž
        ///dva
        ///dve
        ///eha
        ///eh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordList {
            get {
                return ResourceManager.GetString("WordList", resourceCulture);
            }
        }
    }
}
